/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VariantsRouteImport } from './routes/variants'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SigningKeysRouteImport } from './routes/signing-keys'
import { Route as FoldersRouteImport } from './routes/folders'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImagesIndexRouteImport } from './routes/images.index'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ImagesImageIdRouteImport } from './routes/images.$imageId'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'

const VariantsRoute = VariantsRouteImport.update({
  id: '/variants',
  path: '/variants',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SigningKeysRoute = SigningKeysRouteImport.update({
  id: '/signing-keys',
  path: '/signing-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldersRoute = FoldersRouteImport.update({
  id: '/folders',
  path: '/folders',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesIndexRoute = ImagesIndexRouteImport.update({
  id: '/images/',
  path: '/images/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesImageIdRoute = ImagesImageIdRouteImport.update({
  id: '/images/$imageId',
  path: '/images/$imageId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/folders': typeof FoldersRoute
  '/signing-keys': typeof SigningKeysRoute
  '/upload': typeof UploadRoute
  '/variants': typeof VariantsRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/images/$imageId': typeof ImagesImageIdRoute
  '/clients/': typeof ClientsIndexRoute
  '/images/': typeof ImagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/folders': typeof FoldersRoute
  '/signing-keys': typeof SigningKeysRoute
  '/upload': typeof UploadRoute
  '/variants': typeof VariantsRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/images/$imageId': typeof ImagesImageIdRoute
  '/clients': typeof ClientsIndexRoute
  '/images': typeof ImagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/folders': typeof FoldersRoute
  '/signing-keys': typeof SigningKeysRoute
  '/upload': typeof UploadRoute
  '/variants': typeof VariantsRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/images/$imageId': typeof ImagesImageIdRoute
  '/clients/': typeof ClientsIndexRoute
  '/images/': typeof ImagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/folders'
    | '/signing-keys'
    | '/upload'
    | '/variants'
    | '/clients/$clientId'
    | '/images/$imageId'
    | '/clients/'
    | '/images/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/folders'
    | '/signing-keys'
    | '/upload'
    | '/variants'
    | '/clients/$clientId'
    | '/images/$imageId'
    | '/clients'
    | '/images'
  id:
    | '__root__'
    | '/'
    | '/folders'
    | '/signing-keys'
    | '/upload'
    | '/variants'
    | '/clients/$clientId'
    | '/images/$imageId'
    | '/clients/'
    | '/images/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FoldersRoute: typeof FoldersRoute
  SigningKeysRoute: typeof SigningKeysRoute
  UploadRoute: typeof UploadRoute
  VariantsRoute: typeof VariantsRoute
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ImagesImageIdRoute: typeof ImagesImageIdRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  ImagesIndexRoute: typeof ImagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/variants': {
      id: '/variants'
      path: '/variants'
      fullPath: '/variants'
      preLoaderRoute: typeof VariantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signing-keys': {
      id: '/signing-keys'
      path: '/signing-keys'
      fullPath: '/signing-keys'
      preLoaderRoute: typeof SigningKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders': {
      id: '/folders'
      path: '/folders'
      fullPath: '/folders'
      preLoaderRoute: typeof FoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/': {
      id: '/images/'
      path: '/images'
      fullPath: '/images/'
      preLoaderRoute: typeof ImagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/$imageId': {
      id: '/images/$imageId'
      path: '/images/$imageId'
      fullPath: '/images/$imageId'
      preLoaderRoute: typeof ImagesImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FoldersRoute: FoldersRoute,
  SigningKeysRoute: SigningKeysRoute,
  UploadRoute: UploadRoute,
  VariantsRoute: VariantsRoute,
  ClientsClientIdRoute: ClientsClientIdRoute,
  ImagesImageIdRoute: ImagesImageIdRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  ImagesIndexRoute: ImagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
